[package]
name = "reqwest_wiremock"
version = "0.0.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
wiremock = { version = "0.6.2", optional = true }
http = "^1"

[features]
mocking = [
	"dep:wiremock"
]
