/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ActionsGetWorkflowWorkflowIdParameter {
    Integer(i32),
    String(String),
}

impl Default for ActionsGetWorkflowWorkflowIdParameter {
    fn default() -> Self {
        Self::Integer(Default::default())
    }
}

impl std::fmt::Display for ActionsGetWorkflowWorkflowIdParameter {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ActionsGetWorkflowWorkflowIdParameter::Integer(i) => write!(f, "{i}"),
            ActionsGetWorkflowWorkflowIdParameter::String(s) => f.write_str(&s),
        }
    }
}
