/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCommitVerification {
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "signature", deserialize_with = "Option::deserialize")]
    pub signature: Option<String>,
    #[serde(rename = "payload", deserialize_with = "Option::deserialize")]
    pub payload: Option<String>,
}

impl GitCommitVerification {
    pub fn new(
        verified: bool,
        reason: String,
        signature: Option<String>,
        payload: Option<String>,
    ) -> GitCommitVerification {
        GitCommitVerification {
            verified,
            reason,
            signature,
            payload,
        }
    }
}
