/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use super::app_1_permissions::ReadOrWrite;

/// IntegrationPermissions : The set of permissions for the GitHub app
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
/// NOTE: I Changed the types below.
pub struct IntegrationPermissions {
    pub issues: Option<ReadOrWrite>,
    pub checks: Option<ReadOrWrite>,
    pub metadata: Option<ReadOrWrite>,
    pub contents: Option<ReadOrWrite>,
    pub deployments: Option<ReadOrWrite>,
}
