/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, Hash)]
pub struct Reactions {
    #[serde(rename = "+1")]
    pub plus_1: i64,
    #[serde(rename = "-1")]
    pub _1: i64,
    #[serde(rename = "confused")]
    pub confused: i64,
    #[serde(rename = "eyes")]
    pub eyes: i64,
    #[serde(rename = "heart")]
    pub heart: i64,
    #[serde(rename = "hooray")]
    pub hooray: i64,
    #[serde(rename = "laugh")]
    pub laugh: i64,
    #[serde(rename = "rocket")]
    pub rocket: i64,
    #[serde(rename = "total_count")]
    pub total_count: i64,
    #[serde(rename = "url")]
    pub url: String,
}
