/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReactionRollup {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "total_count")]
    pub total_count: i32,
    #[serde(rename = "+1")]
    pub plus_1: i32,
    #[serde(rename = "-1")]
    pub _1: i32,
    #[serde(rename = "laugh")]
    pub laugh: i32,
    #[serde(rename = "confused")]
    pub confused: i32,
    #[serde(rename = "heart")]
    pub heart: i32,
    #[serde(rename = "hooray")]
    pub hooray: i32,
    #[serde(rename = "eyes")]
    pub eyes: i32,
    #[serde(rename = "rocket")]
    pub rocket: i32,
}
