/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SigstoreBundle0VerificationMaterial {
    #[serde(
        rename = "x509CertificateChain",
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_certificate_chain:
        Option<Box<models::SigstoreBundle0VerificationMaterialX509CertificateChain>>,
    #[serde(rename = "tlogEntries", skip_serializing_if = "Option::is_none")]
    pub tlog_entries: Option<Vec<models::SigstoreBundle0VerificationMaterialTlogEntriesInner>>,
    #[serde(
        rename = "timestampVerificationData",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timestamp_verification_data: Option<Option<String>>,
}

impl SigstoreBundle0VerificationMaterial {
    pub fn new() -> SigstoreBundle0VerificationMaterial {
        SigstoreBundle0VerificationMaterial {
            x509_certificate_chain: None,
            tlog_entries: None,
            timestamp_verification_data: None,
        }
    }
}
