[build]
rustflags = ["-Z", "threads=8", "--cfg=web_sys_unstable_apis"]

# [target.aarch64-apple-darwin]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]

[unstable]
codegen-backend = true

[profile.server-dev]
codegen-backend = "cranelift"
