/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Clone)]
pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub bearer_access_token: Option<String>,
    // TODO: take an oauth2 token source, similar to the go one
}

pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

impl Configuration {
    pub fn with_bearer_access_token(self, bearer_access_token: Option<String>) -> Self {
        Self {
            bearer_access_token,
            ..self
        }
    }

    pub fn with_user_agent(self, user_agent: Option<String>) -> Self {
        Self { user_agent, ..self }
    }
}
