[package]
name = "utils"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
backtrace = "0.3.74"
futures = "*"
pin-project = "1.0"
reqwest = "0.12.8"

serde = "1.0.210"
serde_json = "1.0.132"
url = "2.5.2"

[features]
ssr = []
hydrate = []
