CREATE TABLE users (
    avatar_url TEXT NOT NULL,
    bio TEXT,
    blog TEXT,
    business_plus BOOLEAN,
    collaborators BIGINT NOT NULL,
    company TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    disk_usage BIGINT NOT NULL,
    email TEXT,
    events_url TEXT NOT NULL,
    followers BIGINT NOT NULL,
    followers_url TEXT NOT NULL,
    following BIGINT NOT NULL,
    following_url TEXT NOT NULL,
    gists_url TEXT NOT NULL,
    gravatar_id TEXT,
    hireable BOOLEAN,
    html_url TEXT NOT NULL,
    id BIGINT NOT NULL PRIMARY KEY,
    ldap_dn TEXT,
    location TEXT,
    login TEXT NOT NULL,
    name TEXT,
    node_id TEXT NOT NULL,
    notification_email TEXT,
    organizations_url TEXT NOT NULL,
    owned_private_repos BIGINT NOT NULL,
    private_gists BIGINT NOT NULL,
    public_gists BIGINT NOT NULL,
    public_repos BIGINT NOT NULL,
    received_events_url TEXT NOT NULL,
    repos_url TEXT NOT NULL,
    site_admin BOOLEAN NOT NULL,
    starred_url TEXT NOT NULL,
    subscriptions_url TEXT NOT NULL,
    total_private_repos BIGINT NOT NULL,
    twitter_username TEXT,
    two_factor_authentication BOOLEAN NOT NULL,
    type_ TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    url TEXT NOT NULL,
    user_view_type TEXT
);
