name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  non-wasm-tests:
    name: Non-WASM Tests - ${{ matrix.crate }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          - backend
          - typesafe_idb
          - meta_tools
          - macros_impl

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2025-04-28

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests for ${{ matrix.crate }}
        run: cargo test -p ${{ matrix.crate }} -- --test-threads=4

  wasm-tests:
    name: WASM Tests - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [web, shared]
        include:
          - package: web
            working-directory: ./web
            features: ""
          - package: shared
            working-directory: ./shared
            features: "--features hydrate"
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2025-04-28
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run WASM tests
        working-directory: ${{ matrix.working-directory }}
        run: wasm-pack test --headless --firefox ${{ matrix.features }}

