name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

  # Just adding these because tests are failing in CI. Hopefully they are not actually used in CI lol.
  HEIMISCH_OUTPUT_NAME: 'heimisch'
  HEIMISCH_API_DOMAIN: 'http://localhost:3210/'
  HEIMISCH_FRONTEND_DOMAIN: 'http://localhost:3000/'

jobs:
  non-wasm-tests:
    name: Non-WASM Tests - ${{ matrix.crate }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          - backend
          - typesafe_idb
          - meta_tools
          - macros_impl

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-04-28
          # cache is enabled by default

      # Keeping Swatinem/rust-cache for caching dependencies
      # The toolchain itself will be cached by actions-rust-lang/setup-rust-toolchain
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests for ${{ matrix.crate }}
        run: cargo test -p ${{ matrix.crate }} -- --test-threads=4

  wasm-tests:
    name: WASM Tests - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [web, shared]
        include:
          - package: web
            working-directory: ./web
            features: ""
          - package: shared
            working-directory: ./shared
            features: "--features hydrate"
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-04-28
          targets: wasm32-unknown-unknown
          # cache is enabled by default

      # Keeping Swatinem/rust-cache for caching dependencies
      # The toolchain itself will be cached by actions-rust-lang/setup-rust-toolchain
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run WASM tests
        working-directory: ${{ matrix.working-directory }}
        run: wasm-pack test --headless --firefox ${{ matrix.features }}

