[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
# anyhow = { version = "1.0.89", features = ["backtrace"] }
console_error_panic_hook = "0.1"
leptos = { version = "0.6" }
leptos_meta = { version = "0.6" }
leptos_router = { version = "0.6" }
wasm-bindgen = "=0.2.93"
thiserror = "1"
http = "1"

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
